### ISSUE TITLE
Last build break notification

### ISSUE THREAD

**Issue by kosssi** [ptman/drone-plugin-matrix#32]
Hello,

I used [Drone plugin for sending Matrix notifications](https://github.com/drone-plugins/drone-matrix) but it's breaking since [last build](https://hub.docker.com/layers/plugins/matrix/latest/images/sha256-dfb66f9c294d9257f2463c5a16786deff5d796fc1da64bee705423945fddb012?context=explore) when [this pull request "(maint) move to harness.drone.io"](https://github.com/drone-plugins/drone-matrix/pull/30) is merged.

My configuration:

```
- name: notify
  image: plugins/matrix
  settings:
    homeserver: https://***.***
    roomid: "***:***.***"
    userid: "***:***.***"
    accesstoken:
      from_secret: MATRIX_ACCESSTOKEN
  when:
    status: [ failure ]
```

the error:
```
time="2023-01-16T13:37:20Z" level=error msg="execution failed: failed to authenticate user: contents=[123 34 101 114 114 99 111 100 ...] msg=Failed to POST JSON to /_matrix/client/r0/login code=400 wrapped=M_INVALID_PARAM: Bad parameter: password"
```

This error is print from [here](https://github.com/drone-plugins/drone-matrix/blob/d20f7eaaf1904f555d94b067d597bdf5b55e6e72/plugin/impl.go#L52) but I don't understand normally, UserID and AccessToken are not empty...

I found a solution with specified sha256 image but I thinks it's not a good solution ;) :
```
image: plugins/matrix@sha256:f1affb31b0c86963c97c6f976fa0dcb3cc84272057fd8558d609d28b3064bd7f
```

I'm alone?

PS: Akismet hidden [my post](https://community.harness.io/t/drone-plugin-for-sending-matrix-notifications-failed/13188/1) on https://community.harness.io/ because I would like have more than 2 links in my post... 😒
